services:
  - type: worker
    name: dobby-telegram-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: TG_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: DEFAULT_TONE
        value: explanatory
      - key: OPENAI_MODEL
        value: gpt-4o-mini
